spring.application.name=travelbot

spring.ai.mistralai.api-key=GOKIbZi8LMi80EQ7cbFjGhTdZJiatQIW
gemini.api.key=AIzaSyCun2tMlKH1xbdsQAtplez8FnOFIlytQ28
spring.ai.mistralai.chat.options.response-format=json_object
